### ISSUE TITLE
Google Colab: Data not found

### ISSUE THREAD

**Issue by valentinoli** [DAG-EPFL/weekly-challenges-21-spring#1]
Hi, great initiative! 💯 

I opened the first challenge in Google Colab, but unfortunately the demographic data is not there... only some other data files

![image](https://user-images.githubusercontent.com/23453691/111128875-b5a3a280-8575-11eb-80d4-d56a4868c0f4.png)

**Comment by amvjakob** [comment]
Hi @valentinoli, thank your for raising this issue.

If you use Google Colab, the easiest solution is probably to upload the files you need into the file plane on the left side of the screen. The files can be found here: [https://github.com/DAG-EPFL/weekly-challenges-21-spring/tree/main/challenge01/data](https://github.com/DAG-EPFL/weekly-challenges-21-spring/tree/main/challenge01/data). The README has been adapted to include this information.

Of course, you could also opt for a more manual approach and clone the entire repository, either from the command line or from the Google Colab notebook itself. That way, the necessary files will automatically be included at the correct location.

**Comment by valentinoli** [comment]
Ah, I see. Well I ended up cloning it
